### ISSUE TITLE
Remove a few Mads references

### ISSUE THREAD

**Issue by shaggygi** [VsixCommunity/ExtensibilityTemplatePack#13]
While we should definitely praise the founder/lead of this project, would it be appropriate to rename some of the references?  It probably doesn't hurt to have this, but didn't know if it would cause deeper issues in the long-term.  Is there other wording that could represent instead?

See [TemplateID](https://github.com/VsixCommunity/ExtensibilityTemplatePack/blob/86346024ca0322037280c8c6646ee2f2c0a74e65/src/2022/ItemTemplates/ToolWindowCommunity/_Definitions/CSharp.vstemplate#L7) as an example.

**Comment by madskristensen** [comment]
Yes, definitely remove my name. Perhaps replace it with "Community"?
