### ISSUE TITLE
Error when adding a new file

### ISSUE THREAD

**Issue by Shprrr** [VsixCommunity/ExtensibilityTemplatePack#4]
When I add a file (I tried Command (Community) and Async Tool Window (Community)), I get an ArgumentNullException on the parameter filePath and I come back on the window to add a file.

Even if there's an error, the new file is added and the package class is modified to add the command in the InitializeAsync and the attribute when it's a tool window.

Output window on a brand new project:
> Adding a new tool window 'TestToolWindow' to the project 'VSIXProjectCommunity':
>   The tool window will integrate with the 'VSIXProjectCommunity.VSIXProjectCommunityPackage' VS package.
>   The tool window will integrate with the 'VSCommandTable.vsct' command table file.
>   Adding a new attribute [ProvideToolWindow(typeof(TestToolWindow), Style = VsDockStyle.Tabbed, Window = ToolWindowGuids.SolutionExplorer)] to the VS package class 'VSIXProjectCommunityPackage'.
>   Updating method 'InitializeAsync()' in the VS package class 'VSIXProjectCommunityPackage' to call 'await TestToolWindowCommand.InitializeAsync(this);'.
>   Error finishing the new item wizard
>     System.ArgumentNullException: La valeur ne peut pas être null.
> Nom du paramètre : filePath
>    à Microsoft.Vsix.TemplatesPackage.FileUtils.GetRelativePath(String baseDirectory, String filePath)
>    à Microsoft.Vsix.TemplatesPackage.ProjectItemAdaptor.GetRelativePathTo(String otherItemFilePath)
>    à Microsoft.Vsix.TemplatesPackage.VsixWizard.AddVsctButtonIfAny()
>    à Microsoft.Vsix.TemplatesPackage.VsixWizard.RunFinished()

I use VS Entreprise 16.9.3 in French and the error is there on many version of the extension.

**Comment by madskristensen** [comment]
This is a curious one. The templates are using the same wizard under the hood to update the project as the original VS extensibility templates use. However, to make this error go away, I have to add the `/Resources/<commandName>.png` file and the stuff it adds to the .vsct file is terrible. Not sure what to do here

**Comment by Shprrr** [comment]
I don't know if it's related but the output window says that it will integrate the tool window to the vsct file, but it's not there when I look in that file.

```
<?xml version="1.0" encoding="utf-8"?>
<CommandTable xmlns="http://schemas.microsoft.com/VisualStudio/2005-10-18/CommandTable" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <Extern href="stdidcmd.h"/>
  <Extern href="vsshlids.h"/>
  <Include href="KnownImageIds.vsct"/>
  <Include href="VSGlobals.vsct"/>

  <Commands package="guidPackage">
  </Commands>

  <Symbols>
    <GuidSymbol name="guidPackage" value="{de90336d-6a03-41c2-86c7-1e13ea7f6346}" />
  </Symbols>
</CommandTable>
```

**Comment by madskristensen** [comment]
That's because it doesn't handle the error and stops processing the .vsct file

**Comment by madskristensen** [comment]
This is now fixed
